name: Release the unity package
on:
  push:
    branches:
      - develop
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "Assets/Voiceer.meta" > metaList
        find Assets/Voiceer/ -name \*.meta >> metaList

    - run: mkdir a

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'a/output.unitypackage'
        include-files: metaList
    - uses: actions/upload-artifact@master
      with:
        path: a
        name: package