name: Release the unity package
on:
  push:
    branches:
      - develop
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
          restore-keys: Library-
      
      - name: create unitypackage from glob pattern
        uses: natsuneko-laboratory/create-unitypackage@v3
        with:
          files-glob: |
            ./**/*.cs
          dest: dynamicpixels.unitypackage

      # Upload
      - name: Upload .unitypackage
        uses: actions/upload-artifact@v2
        with:
          name: Unity Package
          path: Build
